CREATE SEQUENCE SQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_CONTA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_DESPESA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_INVESTIMENTO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TB_USUARIO (
    ID_USUARIO NUMBER(19) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    CPF VARCHAR2(14) NOT NULL UNIQUE,
    TELEFONE VARCHAR2(20),
    IDADE NUMBER(10) NOT NULL,
    PERFIL VARCHAR2(30) NOT NULL
);

CREATE TABLE TB_CONTA (
    ID_CONTA NUMBER(19) PRIMARY KEY,
    NUMERO_CONTA VARCHAR2(30) NOT NULL UNIQUE,
    TITULAR VARCHAR2(120) NOT NULL,
    SALDO NUMBER(12, 2) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    ATIVA NUMBER(1) NOT NULL
);

CREATE TABLE TB_DESPESA (
    ID_DESPESA NUMBER(19) PRIMARY KEY,
    DESCRICAO VARCHAR2(120) NOT NULL,
    VALOR NUMBER(12, 2) NOT NULL,
    DATA_DESPESA DATE NOT NULL,
    CATEGORIA VARCHAR2(60) NOT NULL,
    FORMA_PAGAMENTO VARCHAR2(40) NOT NULL,
    PAGA NUMBER(1) NOT NULL
);

CREATE TABLE TB_INVESTIMENTO (
    ID_INVESTIMENTO NUMBER(19) PRIMARY KEY,
    DESCRICAO VARCHAR2(120) NOT NULL,
    VALOR NUMBER(12, 2) NOT NULL,
    DATA_INVESTIMENTO DATE NOT NULL,
    CATEGORIA VARCHAR2(60) NOT NULL,
    RENDIMENTO NUMBER(12, 2) NOT NULL,
    TAXA_JUROS NUMBER(8, 4) NOT NULL,
    RESGATADO NUMBER(1) NOT NULL
);
